// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/concepts.tsx";
import * as $1 from "./routes/examples.tsx";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/sources.tsx";
import * as $4 from "./routes/targets.tsx";
import * as $5 from "./routes/transforms.tsx";

const manifest = {
  routes: {
    "./routes/concepts.tsx": $0,
    "./routes/examples.tsx": $1,
    "./routes/index.tsx": $2,
    "./routes/sources.tsx": $3,
    "./routes/targets.tsx": $4,
    "./routes/transforms.tsx": $5,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
